services:
  glance:
    image: glanceapp/glance
    container_name: glance
    restart: unless-stopped
    ports:
      - "8090:8080"
    environment:
      - WEATHER_LOCATION=${WEATHER_LOCATION}
      - WEATHER_UNITS=${WEATHER_UNITS}
      - HOST_IP=${HOST_IP}
      - NAS_IP=${NAS_IP}
      - PIHOLE_API_TOKEN=${PIHOLE_API_TOKEN}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - SONARR_API_KEY=${SONARR_API_KEY}
      - SPEEDTEST_APP_KEY=${SPEEDTEST_APP_KEY}
      - SPEEDTEST_TRACKER_API_TOKEN=${SPEEDTEST_TRACKER_API_TOKEN}
    volumes:
      - /opt/docker/glance-dashboard-config/glance/glance.yml:/app/config/glance.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro