services:
  glance:
    image: glanceapp/glance
    container_name: glance
    restart: unless-stopped
    ports:
      - "8090:8080"
    volumes:
      - /opt/docker/glance-dashboard-config/glance/glance.yml:/app/config/glance.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro