services:
  dynacat:
    image: panonim/dynacat
    container_name: dynacat
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=Pacific/Auckland
      - HOST_IP=${HOST_IP}
      - WEATHER_LOCATION=${WEATHER_LOCATION}
      - SPEEDTEST_TRACKER_API_TOKEN=${SPEEDTEST_TRACKER_API_TOKEN}
      - SEERR_API_KEY=${SEERR_API_KEY}
    volumes:
      - /opt/docker/glance-dashboard-config/dynacat:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
